### PR TITLE
URL-escape postgres connection string

### LINKED ISSUE #8: Postgres connection fails when password contains spaces

### PR DESCRIPTION
**Pull request by sydneyli**
Fixes #8.
Larger `fmt.Println => log.Println` refactor incoming to support #9

### CODE REVIEW

**Comment by vbrown608** [comment]
When I try to connect with a password that includes spaces I still see
```
parse postgres://vivian:[redacted thing with unescaped spaces]@localhost/starttls?sslmode=disable: net/url: invalid userinfo
```
when I log the error

File: db/sqldb.go [hunk 1]
```diff
@@ -16,10 +18,19 @@ type SqlDatabase struct {
     Conn *sql.DB
 }
 
-func InitSqlDatabase(cfg Config) (*SqlDatabase, error) {
+func getConnectionString(cfg Config) string {
     connectionString := fmt.Sprintf("postgres://%s:%s@%s/%s?sslmode=disable",
                                     cfg.Db_username, cfg.Db_pass, cfg.Db_host, cfg.Db_name)
-    fmt.Printf("Connecting to %s ... \n", connectionString)
+    u, err := url.Parse(connectionString)
```
Comment (vbrown608) [inline db/sqldb.go]: When `connectionString` contains spaces, `url.Parse` fails for me with the error
```
parse postgres://vivian:password with spaces@localhost/starttls?sslmode=disable: net/url: invalid userinfo
```

Calling `url.PathEscape(cfg.Db_pass)` before building the string seems to work. Any attempts to escape later seem to escape other important components of the URL.

**Comment by vbrown608** [comment]
:100:
